compiler:clang-cl
src_dir:.
build_dir:build\simple_async_tcp_echo_server\debug\
intermediate_dir:build\simple_async_tcp_echo_server\debug\intermediate\
output_name:simple_async_tcp_echo_server.exe
log_dir:forgescript\log\simple_async_tcp_echo_server\debug\
include_dirs:..\..\include\
lib_dirs:..\..\build\firelink\debug\
libs:firelink
compiler_flags:/Zi;/Od;/Wall;/MDd;/std:c++latest;-Wno-c++98-compat;/clang:-Wno-language-extension-token
linker_flags:/DEBUG:FULL